// Feature-based hooks exports
export * from './student';
export * from './teacher';
export * from './academic';
export * from './attendance';
export * from './financial';
export * from './library';
export * from './admin';
export * from './communication';